### ISSUE TITLE
Crash with Android 4.1 with ArrayMap

### ISSUE THREAD

**Issue by princeHago** [pavlospt/RxFile#12]
Hi,

i'm using your component but it will crash when i use my app on android 4.1, follow the trace

`FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                             java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                 at java.lang.Thread.run(Thread.java:856)
                                                                              Caused by: java.lang.ExceptionInInitializerError
                                                                                 at com.pavlospt.rxfile.RxFile.isMediaUri(RxFile.java:479)
                                                                                 at com.pavlospt.rxfile.RxFile.access$300(RxFile.java:49)
                                                                                 at com.pavlospt.rxfile.RxFile$4.call(RxFile.java:191)
                                                                                 at com.pavlospt.rxfile.RxFile$4.call(RxFile.java:180)
                                                                                 at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:32)
                                                                                 at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:17)
                                                                                 at rx.Observable.unsafeSubscribe(Observable.java:8171)
                                                                                 at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390) 
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153) 
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                                                 at java.lang.Thread.run(Thread.java:856) 
                                                                              Caused by: java.lang.NoClassDefFoundError: android.util.ArrayMap
                                                                                 at com.pavlospt.rxfile.Constants.<clinit>(Constants.java:79)
                                                                                 at com.pavlospt.rxfile.RxFile.isMediaUri(RxFile.java:479) 
                                                                                 at com.pavlospt.rxfile.RxFile.access$300(RxFile.java:49) 
                                                                                 at com.pavlospt.rxfile.RxFile$4.call(RxFile.java:191) 
                                                                                 at com.pavlospt.rxfile.RxFile$4.call(RxFile.java:180) 
                                                                                 at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:32) 
                                                                                 at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:17) 
                                                                                 at rx.Observable.unsafeSubscribe(Observable.java:8171) 
                                                                                 at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62) 
                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390) 
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:234) 
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153) 
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                                                 at java.lang.Thread.run(Thread.java:856) `

ArrayMap was introduced in Api level 19, but it was also released in the compatibility library v4, so it would be enough to change the import to android.support.v4.util.ArrayMap instead of android.util.ArrayMap.

Can you fix it?

Thanks in advance.

**Comment by pavlospt** [comment]
@princeHago Hello, you can always submit a PR fixing this :)

**Comment by princeHago** [comment]
i do it (i hope, is the first commit for me on github). can you approve it?

**Comment by pavlospt** [comment]
Thanks for the PR, will try to upgrade the repo in whole as well and import your change!

**Comment by princeHago** [comment]
why you change the minimum api level? now is 19 but before was 17, my api level...

i change the import for this compatibility

**Comment by pavlospt** [comment]
@princeHago API level was bumped due to the following issue https://github.com/pavlospt/RxFile/issues/8. If this is breaking for your app I am sorry but I can not support below 19 :)

**Comment by princeHago** [comment]
API >= 19 is too lastest, can we try a workaround for [#8](https://github.com/pavlospt/RxFile/issues/8) and decrease the api level?

**Comment by pavlospt** [comment]
I am also planning to upgrade to RxJava2 as well which means that `null` is out of the game! Not sure if there is a workaround!
